syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "CommentService.Presentation.Grpc.Protos";

package posts;

service CommentService {
  rpc CreateComment (CreateCommentRequest) returns (CreateCommentResponse);
}

message Comment {
  string comment_id = 1;
  string content = 2;
  string author_user_id = 3;
  string post_id = 4;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message CreateCommentRequest {
  string content = 1;
  string author_user_id = 2;
}

message CreateCommentResponse {
  string comment_id = 1;
}
